server:
  port: 9999
  display-name: "boot-rabbit"
spring:
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: live-mall
    username: guest
    password: guest
    publisher-confirms: true



#  spring.rabbitmq.host=localhost
#  spring.rabbitmq.port=5672
#  spring.rabbitmq.virtual-host=/
#  spring.rabbitmq.username=guest
#  spring.rabbitmq.password=guest
#  spring.rabbitmq.publisher-confirms=true